sudo: required
  
language: python

services:
  - docker

before_install:
  - docker build -t app-test -f docker/Dockerfile.test .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run -t app-test /bin/bash -c "pytest && $ci_env"

